apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinger-deploy
spec:
  selector:
    matchLabels:
      app: pinger
  replicas: 1
  template:
    metadata:
      labels:
        app: pinger
    spec:
      containers:
        - name: pingerapp
          image: ilniko/pinger
          command: ["printenv"]
          args: ["MY_HOST"]
          env:
            - name: MY_HOST
              valueFrom:
                secretKeyRef:
                  name: pinger-secret
                  key: host_name