version: "3.9"

volumes:
  redis-app:

services:
  redis:
    image: redis:alpine
  flask-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - redis-app:/code
    depends_on:
      - redis
