apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: myvar
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}-configmap
                  key: var1
            - name: myvar2
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secret
                  key: var2
