apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: tap-nik-cluster
  region: eu-west-1

iam:
  withOIDC: true

nodeGroups:
  - name: tap-nik-ng-1
    instanceType: t3.small
    minSize: 2
    maxSize: 4
    desiredCapacity: 2
    volumeSize: 20
    privateNetworking: true
    iam:
      withAddonPolicies:
        autoScaler: true
        efs: true
    tags:
      # EC2 tags required for cluster-autoscaler auto-discovery
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/cluster-13: "owned"