apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: access-pods
  namespace: default
subjects:
- kind: ServiceAccount
  name: test-user
roleRef:
  kind: Role
  name: pod-access
  apiGroup: rbac.authorization.k8s.io