apiVersion: apps/v1
kind: Deployment
metadata:
  name: memstress
  namespace: mem-default
spec:
  selector:
    matchLabels:
      app: memtest
  replicas: 1
  template:
    metadata:
      labels:
        app: memtest
    spec:
      containers:
      - name: polinuxstress
        image: polinux/stress
        resources:
          requests:
            memory: 50Mi
          limits:
            memory: 100Mi
        command: ["/usr/local/bin/stress"]
        args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
